# -*- coding: utf-8 -*-
"""Elite.ai-Web-Scrapings

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cvNI9RDjLGjrYCwnRpS6Hf-pqx7gl17T
"""

import requests
from bs4 import BeautifulSoup
import re

class BasicScraping():

  def __init__(self, URL):
    self.URL = URL
    r = requests.get(self.URL)
    self.response_obj = r
    soup = BeautifulSoup(self.response_obj.content, 'html5lib')
    self.soup_obj = soup
    self.domain_name = re.findall('https://(.*?).com/', self.URL)[0]
    

  def print_structure(self):
    print(self.soup_obj.prettify())
  
  def get_text_content(self):

    if self.domain_name == "machinelearningmastery":
      text = ""
      sec = self.soup_obj.find('section', attrs={'id':'main'})
      for ele in sec.findAll(['p']):
        text += ele.text + "\n"
      return text

if __name__ == '__main__':
  bs = BasicScraping('https://machinelearningmastery.com/data-preparation-techniques-for-machine-learning/')
  bs.print_structure()
  text = bs.get_text_content()

